controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
test_action:
    path: /lucky/test
    controller: App\Controller\LuckyController::test